server:
  port: 8080

spring: 
  r2dbc: 
    url: r2dbc:h2:mem:///apigw
    username: sa
    password:
    pool:
      enabled: true
  datasource:
    initialization-mode: always
  h2:
    console:
      enabled: true
      path: /h2-console

logging.level.org.springframework.r2dbc: DEBUG