DROP TABLE IF EXISTS APP_CLIENT;
CREATE TABLE APP_CLIENT
(
    CLIENT_KEY    SERIAL        NOT NULL,
    CLIENT_ID     VARCHAR(100)  NOT NULL,
    CLIENT_SECRET VARCHAR(500)  NOT NULL,
    CONNECT_URL   VARCHAR(100)  NOT NULL,
    DELETED       BOOLEAN       NULL,
    REASON        VARCHAR(1000) NULL,
    PRIMARY KEY (CLIENT_KEY)
);
ALTER TABLE APP_CLIENT
    ADD CONSTRAINT APP_CLIENT_UX_01 UNIQUE (CLIENT_ID)